project:
  type: website
  output-dir: docs

website:
  title: "Transit Fragmentation"
  navbar:
    left:
      - href: index.qmd
        text: Analysis
      - href: DEFICIT_MAP.qmd
        text: Deficit Map
      - href: TRANSIT_MAP.qmd
        text: Fragmentation Map

format:
  html:
    theme: flatly
    toc: true
    toc-depth: 3
    linestretch: 1.6
    code-fold: true
    highlight-style: github
    df-print: kable
    page-layout: article
